Traceback (most recent call last):
  File "C:\Conda\envs\tester\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Joshua Agar\AppData\Roaming\Python\Python310\site-packages\nbclient\client.py", line 1263, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Joshua Agar\AppData\Roaming\Python\Python310\site-packages\nbclient\util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Joshua Agar\AppData\Roaming\Python\Python310\site-packages\nbclient\util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "C:\Conda\envs\tester\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Joshua Agar\AppData\Roaming\Python\Python310\site-packages\nbclient\client.py", line 701, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Joshua Agar\AppData\Roaming\Python\Python310\site-packages\nbclient\client.py", line 1019, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Joshua Agar\AppData\Roaming\Python\Python310\site-packages\nbclient\client.py", line 913, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
from skimage import io
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import inspect

from m3_learning.util.code import print_code


from m3_learning.viz.nn import embeddings, latent_generator
from m3_learning.nn.random import random_seed
from m3_learning.viz.style import set_style
from m3_learning.nn.time_series_nn.nn_util import Train, transform_nn, loss_function
from m3_learning.viz.layout import layout_fig, embedding_maps
from m3_learning.util.data_generators import generate_data

import copy
import torch
import torch.nn as nn
import torch.optim as optim
from torchsummary import summary

set_style("default")
random_seed(seed=42)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn [2], line 7[0m
[0;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[0;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01minspect[39;00m
[1;32m----> 7[0m [38;5;28;01mfrom[39;00m [38;5;21;01mm3_learning[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutil[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcode[39;00m [38;5;28;01mimport[39;00m print_code
[0;32m     10[0m [38;5;28;01mfrom[39;00m [38;5;21;01mm3_learning[39;00m[38;5;21;01m.[39;00m[38;5;21;01mviz[39;00m[38;5;21;01m.[39;00m[38;5;21;01mnn[39;00m [38;5;28;01mimport[39;00m embeddings, latent_generator
[0;32m     11[0m [38;5;28;01mfrom[39;00m [38;5;21;01mm3_learning[39;00m[38;5;21;01m.[39;00m[38;5;21;01mnn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mrandom[39;00m [38;5;28;01mimport[39;00m random_seed

[1;31mModuleNotFoundError[0m: No module named 'm3_learning.util.code'
ModuleNotFoundError: No module named 'm3_learning.util.code'

